keys:
  - &admin_wsl ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINnQzm0m6//bLp280evhqpKpiZzId73nCvFYfxWorgvh xiaoxi@DESKTOP-DGBCL6B
  - &matrix_server age1tdmxh36lc3797urgsqmnm2krrarzpyc9gmms9wvw3wcc6fplwqhsrw3mln
  - &laptop_gentoo ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGFwjywVaKzp0NAzG9azWjif1dZu6KXHQjQUA3Aw5uGT laptop_gentoo

creation_rules:
  - path_regex: MatrixServer/secrets/.*\.ya?ml$
    key_groups:
      - age:
          - *admin_wsl
          - *matrix_server
          - *laptop_gentoo
