Domain = "ygg.xiaoxi654.dn42"
BaseURL = "https://ygg.xiaoxi654.dn42"
InstanceName = "Izumi Network Drasl"
ApplicationOwner = "Izumi Network"
ListenAddress = "127.0.0.1:8001"
DefaultAdmins = [ "xiaoxi654@outlook.com" ]
AllowPasswordLogin = false

[RegistrationNewPlayer]
Allow = true

[[RegistrationOIDC]]
Name = "dn42"
Issuer = "https://oauth.dn42"
ClientID = "c8073f70009afa3511f673bfcd0315d8"
RequireInvite = false
PKCE = true
AllowChoosingPlayerName = true
